### ISSUE TITLE
Add command for standard CSV export of wallet transactions for taxes

### ISSUE THREAD

**Issue by QuadraQ** [decred/decrediton#1133] opened 2018-02-01 07:05 UTC
Please add support for CSV export of transactions similar to the standard export available in most bitcoin core based wallets. Attached is a simplified example. Obviously an optional date range would be very helpful, but not essential. An option to only export coins earned through staking would also be very useful.

[BATL EXPORT.csv.zip](https://github.com/decred/decrediton/files/1684463/BATL.EXPORT.csv.zip)

**Comment by matheusd** [comment] 2018-02-01 09:17
Duplicate of https://github.com/decred/decrediton/issues/912

**Comment by matheusd** [comment] 2018-02-01 09:48
Ok, just saw the chat history now, so I'm reopening but by the context, it seems this should be opened on dcrwallet (as jrick will do a cmdline tool to export the data). The Decrediton work is still covered under #912.

**Comment by alexlyp** [comment] 2018-02-16 15:05
First pass has been completed here: #1136

**Closed by alexlyp** 2018-02-16 15:05 UTC
Labels: duplicate
