### ISSUE TITLE
Too Low Contrast in History of Transactions View When No Transactions

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1591] opened 2018-08-14 19:47 UTC
I can barely see the text "No transactions found".
See 
<img width="1146" alt="poor contrast" src="https://user-images.githubusercontent.com/921390/44114397-5493cc38-a00b-11e8-8c15-5aaa8329a82d.png">

**Comment by cosmicvs** [comment] 2018-08-14 20:10
Which scripting languages are you making use of

**Comment by Jujhar** [comment] 2018-08-14 23:59
I can tackle this.

**Comment by alexlyp** [comment] 2018-08-15 14:52
Duplicate of issue #1582

**Closed by alexlyp** 2018-08-15 14:52 UTC
