### ISSUE TITLE
Startup screen says ticket was revoked, but output indicates otherwise

### ISSUE THREAD

**Issue by taoteh1221** [decred/decrediton#1002] opened 2017-12-17 22:05 UTC
So I just had a ticket vote fine, BUT Decrediton thinks the ticket was revoked, and displays a warning on the startup screen to revoke the ticket with a 'revoke' button. I did NOT push the button, instead went to the transaction details by clicking on the transaction, and the output is larger than the input, indicating the vote was successful and I received my reward in DCR (just like dcrstats says it did). 

This is using Decrediton 1.1.2 on Ubuntu, and a stake pool. I'm guessing there is a false positive here? Also, there is no more 'rescan' button anywhere, which always fixed missing vote transaction details in the past for me. I'm going to restart Decrediton and see if anything corrects itself, or if I at least get a 'rescan' button appearing somewhere to hit to re-scan the perceived state status.

**Comment by taoteh1221** [comment] 2017-12-17 22:14
So upon shutting down Decrediton, and restarting it, the false positive ticket revocation prompt went away. Everything seems as it should be showing the current state.

**Comment by alexlyp** [comment] 2017-12-18 13:39
Yah this is a duplicate of #1000

**Closed by alexlyp** 2017-12-18 13:39 UTC
