### ISSUE TITLE
Make decredition fit smaller screen sizes

### ISSUE THREAD

**Issue by andrewfenn** [decred/decrediton#649] opened 2017-09-09 11:13 UTC
A lot of people (myself included) use laptops and monitors that are 1366x768. Due to this the Decredition application is larger than the desktop size by about 20-40 px. I would recommend making the total application shorter vertically by 40 px so that it nicely fits on those desktop sizes.

Another method would be to change what happens when you resize the application vertically. Right now when I resize the window and make it smaller the "total balance" at the bottom gets hidden, along with the "balance" and logo at the top.

**Comment by taoteh1221** [comment] 2017-09-09 12:59
I can confirm the same issue with a 19" LCD monitor. It also mostly hides confirmation alerts after performing certain actions on my setup, as the alerts are displayed in the right side of the header area.

**Comment by matheusd** [comment] 2017-09-09 21:14
This is being worked on, but depends first on #528.
Possible duplicate of #133.

**Comment by alexlyp** [comment] 2017-09-11 19:49
I'll leave this one open so others can hopefully see it, but yah we are working quickly to make this a reality

**Closed** 2017-09-19 15:34 UTC
Labels: enhancement
