### ISSUE TITLE
1.3 RC2 issue: Error creating wallet

### ISSUE THREAD

**Issue by noahpierau** [decred/decrediton#1653] opened 2018-09-18 11:16 UTC
When you want to cancel creating a new wallet on 1.3 RC2 (while you are already shown the seed), clicking the `cancel` button or the top right `X` gives you an "Error creating wallet" message.

After closing the wallet and restarting it, the name of the failed wallet shows up in the welcome screen with the message "Setup Incomplete" as shown below: 
![image](https://user-images.githubusercontent.com/16287891/45683711-99f5e780-bb44-11e8-9d01-274bcce85b4a.png)

When you click "Launch Wallet" here, Decrediton shuts down without warning.

This issue was found and replicated on a Windows 64-bit device.

**Comment by matheusd** [comment] 2018-09-18 11:58
Verified it's only a problem in windows. The issue is that the wallet is not really stopped, so when attempting to remove the OS complains about the wallet file being in use.

PR #1647 seems to fix it already, since it allows the wallet process to correctly terminate and close its file handles prior to deleting the data.

**Closed** 2018-10-09 16:16 UTC
