### ISSUE TITLE
[1.4.0rc] Blank screen after wallet deletion.

### ISSUE THREAD

**Issue by dnldd** [decred/decrediton#1914] opened 2018-12-16 20:00 UTC
Deleting the only wallet on decrediton leaves it on a blank white screen, should be reloading the launcher.

![wallet 1](https://user-images.githubusercontent.com/1281030/50058208-e2856700-016c-11e9-8759-f9fe5918aeea.png)

![wallet 2](https://user-images.githubusercontent.com/1281030/50058210-eb763880-016c-11e9-8cf1-c3638715731b.png)

![wallet 3](https://user-images.githubusercontent.com/1281030/50058222-1e203100-016d-11e9-8fef-7fd0088eba51.png)

![wallet 4](https://user-images.githubusercontent.com/1281030/50058226-2a0bf300-016d-11e9-83a3-f136dc2f19bd.png)

**Comment by matheusd** [comment] 2018-12-17 13:59
Duplicate of #1886

**Closed by matheusd** 2018-12-17 13:59 UTC
