### ISSUE TITLE
[1.6.0-rc4] Ticket-Status Sync FeeErrors Modal can not be closed

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#3035] opened 2020-12-02 19:04 UTC
On the Ticket-Status Tab initiating a Fee Sync opens a modal window. This modal can not be closed when clicking on the 'cancel' button.

**Comment by amassarwi** [comment] 2020-12-02 19:25
Duplicate of #3026

**Closed** 2020-12-02 19:30 UTC
