### ISSUE TITLE
[1.5.0 RC2] UI Theme change bug

### ISSUE THREAD

**Issue by d146t** [decred/decrediton#2359] opened 2019-12-04 08:59 UTC
This happens on MacOS 10.13.6

when switching the UI theme tonality from dark to light and going back to the governance voting page the projects under vote are duplicated: 

<img width="925" alt="20191204_UI theme01" src="https://user-images.githubusercontent.com/46449825/70128083-903e9e00-167c-11ea-96df-2896a732a99a.png">
<img width="926" alt="20191204_UI theme02" src="https://user-images.githubusercontent.com/46449825/70128086-903e9e00-167c-11ea-9eb8-c3c258b28988.png">

**Comment by jholdstock** [comment] 2019-12-04 12:34
Possibly related/duplicate of #2269
Supposedly fixed in #2284

**Comment by matheusd** [comment] 2019-12-09 13:20
Tested switch back and forth a bunch of times, but wasn't able to reproduce it this way (on latest master).

**Closed** 2020-01-24 14:53 UTC

**Comment by d146t** [comment] 2020-01-24 14:55
The issue doesn't reproduce in decrediton latest version.
