### ISSUE TITLE
Ticket statistics/missed and gui updates after a rescan

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#1000] opened 2017-12-16 12:22 UTC
When i launch decrediton it Tickets tab displays missed votes on blocks that happened during decrediton was shut down/offline.

So after i start decrediton i have to initiate a rescan which cleans the missed/vote count and displays it correct on the Tickets tab / Purchase Tickets section. But the rescan does not update the counts on the Tickets tab / My Tickets section.

**Comment by jiecut42** [comment] 2017-12-17 16:41
+1

**Comment by taoteh1221** [comment] 2017-12-17 22:35
Not sure if my open issue is a duplicate of this, but maybe: https://github.com/decred/decrediton/issues/1002

**Comment by matheusd** [comment] 2017-12-18 12:20
Related to #993.

**Comment by alexlyp** [comment] 2017-12-18 13:39
Not sure it's related to #993 

I believe it's an issue from dcrwallet that is essentially creating false positive missed and seemingly can't be revoked.  I'll be doing deeper dive on this soon to try and figure out the problem.

**Comment by matheusd** [comment] 2017-12-19 13:47
I thought it was related to #993 due to this:

> [...] displays it correct on the Tickets tab / Purchase Tickets section. But the rescan does **not update the counts on the Tickets tab / My Tickets** section.

#1010 added the fetch for GetTickets after a rescan, so at least this part should be fixed.

**Comment by alexlyp** [comment] 2017-12-20 16:05
Right this is partially related to #993, but I believe there to be a deeper issue in dcrwallet that is not counting missed tickets properly. As we discussed on slack, adding a better "dcrwallet has tickets to revoke notification" would be the best way to solve this.

**Comment by matheusd** [comment] 2018-05-10 14:08
Another report from user:

>  as a know failure the voting counts missed tickets on launch of decrediton until you do a rescan. now my observation was: if i have no internet connection launching decrediton i get a "can not connect to stakepool" error. when i immediatly switch on the internet connection after that error message it correctly parses the blockchain and i am not running in the missed-ticket issue

**Closed** 2019-05-15 16:55 UTC
