### ISSUE TITLE
Space missing after key properties words 'Accounts' (v1.1.2)

### ISSUE THREAD

**Issue by nbenci** [decred/decrediton#999] opened 2017-12-16 06:14 UTC
Spaces are missing behind 'external' 'internal' in 'Accounts > Account properties > Keys'

Wallet has >1 accounts created.

Example: 'Keys19 external19 internal0 imported'

**Comment by davecgh** [comment] 2017-12-16 06:23
Duplicate of #994

**Closed** 2017-12-18 11:02 UTC
