### ISSUE TITLE
[1.3.1] Negative amounts in "Balance" overview

### ISSUE THREAD

**Issue by pmknutsen** [decred/decrediton#1966] opened 2018-12-27 11:57 UTC
This has occurred a couple of times when leaving Decredition open during hibernation. Unfortunately, have not found a way to consistently reproduce. Ubuntu 18.04, Decredition 1.3.1:
https://i.imgur.com/8BAXHEW.png

**Comment by matheusd** [comment] 2018-12-27 13:38
This is a known issue and 1.3.1 (eg: #1933)  and should have been resolved for 1.4.0. Mostly caused by unmined tickets not being accounted correctly in the charts.

If you are willing to test the 1.4.0rc1 and report back (please notice the downgrade warnings) or still have after the release of 1.4.0 final, please open up the issue again.

Closing for the moment as this should be already fixed in the next version.

**Comment by szpasztor** [comment] 2019-01-16 21:12
Still happening in 1.4.0 (yarn dev): 
![image](https://user-images.githubusercontent.com/8398290/51277977-861a9f00-19d9-11e9-9c3c-5f58f392a8d7.png)

After a restart it seems OK: 
![image](https://user-images.githubusercontent.com/8398290/51278434-dfcf9900-19da-11e9-92a8-47da76c35e63.png)

Context: auto ticket buyer was running when I closed the wallet and returned to the launcher. The negative balance appeared after this. 

Also, the following logs were printed shortly before the issue, might be related:
```
Error: 2 UNKNOWN: wallet.PublishUnminedTransactions:: dcrd.jsonrpc.sendrawtransaction: -1:
Rejected transaction 
4384829932ef0412760ba34023db8684e85c2383fd78503b785deba490bf2eec: transaction 	
4384829932ef0412760ba34023db8684e85c2383fd78503b785deba490bf2eec expired at height 112608
```

@matheusd can you reopen the issue? I don't have the option to do so.

**Comment by pmknutsen** [comment] 2019-02-18 08:03
Can confirm this is still an issue in 1.4.0. Context this time: computer opened from hibernation, decredition already open and 10 hours behind. Blockchain synched. All ok. Went into ticker buyer, manually purchased a ticket. Returned to Overview and the charts flipped as reported earlier. This time, it was momentary. After a few minutes the chart returned to normal.

**Comment by vctt94** [comment] 2020-03-27 14:20
As I haven't noticed this for a while I am closing this for now. 

We can re-open or have a new issue if reported.

**Closed by vctt94** 2020-03-27 14:20 UTC
