### ISSUE TITLE
ReactToolTip reload without mouse move

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#570] opened 2017-08-09 16:14 UTC
As seen when you click Hide/Show on account, should immediately update to the opposite word without having to issue a mouse move event.

**Comment by Thoughtscript** [comment] 2017-10-04 06:38
@alexlyp - Hey! I've made the change per by adding an onClick function passed in from Sidebar/index.js - I tried to follow the conventions laid out in app/components/CreateWalletForm/.  The sidebar overlay will now disappear or show when the user clicks on the little triangle and will disappear correctly when they mouse away. Since I'm new, I'm still adjusting to the commit conventions :)

I created a feature branch locally and have been trying to commit but can't. Is there some permission or special step I should take? Thanks!

**Comment by Thoughtscript** [comment] 2017-10-04 07:13
Please disregard the permission issue above. Thanks!

**Comment by Thoughtscript** [comment] 2017-10-07 08:30
OK, after getting clearer on the requirement (this pertains to the non-default non-imported account under 'Accounts' and the ability to hide/show it with the little eye button and the corresponding tool-tip) I think the issue is best resolved by waiting for a fix to React-tooltip for a similar issue: https://github.com/wwayne/react-tooltip/pull/281 - not trying to cop out here :)

I've tried several different approaches over the last half day (please note that the related React-Tooltip issue above took several days to resolve and remains yet unmerged). I could be very wrong belong but think I have a pretty good grasp on this surprisingly difficult issue.

Right now, a DOM element is rendered based on the *hidden* prop passed in. That DOM element supplies the data for the ReactTooltip DOM element. This is what gets updated onComponentUpdate through ReactTooltip.rebuild(). Unfortunately, rebuilding doesn't automatically update the tooltip text. I've tried a couple approaches (ok ok more like four or five) and couldn't get it to update correctly:

(1) Adding in additional ReactTooltip.rebuild()'s either without the hidden check, in the onclick functions, and elsewhere. That SHOULD work in the sense that ReactTooltip really SHOULD update dynamically but it still requires a mouse move event. The relevant method is mentioned in the ReactTooltip issue above.

```js
componentDidUpdate(prevProps, prevState) {
	ReactTooltip.rebuild();
    if(prevState.hidden != this.state.hidden) {
      // The tooltips need to be rebuilt because either the Show or Hide button
      // is now being rendered.
      ReactTooltip.rebuild();
    }
  }
```

Was curious to see if two in a row would trigger the event correctly (not ideal but curious)? No change.

(2) So, disappointed, I tried spoofing a mouse-move event. Forcing some event to fire that would make the Tooltip update. There aren't methods exposed on the prototype and the recommended approach is to set a data-event on the HTML element for custom events.

(3) Hover, click, and focus all result in the same behavior when passed in as a data-event:

```html
   <div
   key={"renameAccountButton"+account.accountNumber}
   className="rename-account-button"
   onClick={showRenameAccount}
   data-event="click"
   //data-event="hover"
   data-tip={intl.formatMessage(messages.renameAccountTip)}/>:
```

I might have done this wrong. There are some pretty clear examples here: http://wwayne.com/react-tooltip/ though they differ a bit since the elements are static and the main issue here is that we are rerendering on the basis of state change.

(4) One of the more promising approaches was to use the getContent feature. http://wwayne.com/react-tooltip/ has an example at the bottom where a single, static, element can point at a ReactTooltip element via *data-for* generating a dynamically updated tooltip. This is actually the crux of the ReactTooltip issue I listed at the start. Problem here is that when we pass in a newly generated element each time, the empty data for overrides the getContent() method's return value.

```js
    <div className="account-actions">
             {account.accountName !== "imported" ?
               <div
                 key={"renameAccountButton"+account.accountNumber}
                 className="rename-account-button"
                 onClick={showRenameAccount}
                 data-tip={intl.formatMessage(messages.renameAccountTip)}/>:
               <div></div>
             }
             {account.accountName !== "imported" && account.accountName !== "default" && account.total == 0 && !hidden ?
               <div
                 key={"hideAccountButton"+account.accountNumber}
                 className="hide-account-button"
                 onClick={hideAccount}
                 data-for="accountTip"
                 data-tip={intl.formatMessage(messages.hideTip)}/>:
               account.accountName !== "imported" && account.accountName !== "default" && hidden ?
                 <div
                   className="show-account-button"
                   key={"showAccountButton"+account.accountNumber}
                   onClick={showAccount}
                   data-for="accountTip"
                   data-tip={intl.formatMessage(messages.showTip)}/>:
                 <div></div>
             }
           </div>
           <ReactToolTip id="accountTip" type="info" effect="solid" getContent={[() => { return intl.formatMessage(messages.showTip); }]}/>
```

So, the upshot ... none of the things I tried can get around the need to just mouse move. Again, I might have missed something.

Apparently there's a related issue #755 that this may be related to. My hope was to provide an answer to both and maybe even chime in on the ReactTooltip repo's issue.

Any suggestions? Should I just let this rest and move on to another one? Thanks.

**Comment by Thoughtscript** [comment] 2017-10-07 08:33
@alexlyp - please forgive the lengthy comments above - wanted to give a thorough explanation and touch-base.

**Comment by Thoughtscript** [comment] 2017-10-07 08:39
@alexlyp - Oh wait nevermind... I think I just solved it :)

**Comment by Thoughtscript** [comment] 2017-10-07 08:49
Confirming solved - will check in tomorrow... going to bed

**Closed** 2017-10-18 20:11 UTC
Labels: bug
