### ISSUE TITLE
[v1.4.0RC2] Governance tab multi issue

### ISSUE THREAD

**Issue by Guang168** [decred/decrediton#1990] opened 2019-01-16 16:14 UTC
v1.4.0 RC2 - Governance tab - 3 issues.

1. Treasury balance incorrect - shows 5900+ DCR left.
2. Overlap of the votes bar with props details.
3. No show of how many votes i have until cast vote is clicked

<img width="1062" alt="screen shot 2019-01-17 at 12 05 37 am" src="https://user-images.githubusercontent.com/43533453/51262114-a6a02480-19ec-11e9-89fe-319c78e9bcde.png">

**Comment by alexlyp** [comment] 2019-01-16 16:27
1) Hmm unable to reproduce that.  It's showing the expected 595708... for me.
2) Can fix that for the release.
3) That will have to implemented and will not be available for this release.

**Comment by Guang168** [comment] 2019-01-16 16:32
1. its showing correct for me now as well. but somehow i did manage to screenshot the error balance. will keep monitor and report if i see it again.

**Comment by alexlyp** [comment] 2019-01-16 16:40
OK, cool.  Maybe we can add some sanity checks to avoid showing a vastly too small amount there.

**Comment by Guang168** [comment] 2019-01-16 16:59
by the way i was trying hard to click a few times on the numbers hoping it would bring me to an explorer of the treasury address. Maybe we could do a link ?

**Comment by alexlyp** [comment] 2019-01-16 17:17
yah we can add that

**Comment by oregonisaac** [comment] 2019-03-30 07:34
We have another report of the issue on DCR 101 right now from Pascal at PolyGrowth:
![image](https://user-images.githubusercontent.com/4402603/55273087-7cd46b00-5283-11e9-8cf9-a10a933be955.png)

**Comment by vctt94** [comment] 2019-11-25 10:15
As the others issue related to this issue are fixed, I'll being closing this issue as we now have a new one representing the treasury amount.

**Closed by vctt94** 2019-11-25 10:15 UTC
