### ISSUE TITLE
[travis]  Properly produce packaged versions with travis.

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1834] opened 2018-11-26 18:27 UTC
Since travis will do some automatic publishing in certain scenarios when packaging (apparently osx), we should properly prepare the packages for usage in this published situation.

We need to add dcr* binaries to be able to be added to the bin/ directory that will be used during packaging.  Ideally we should be able to produce dcr* binaries based on a given commit (for situations that require an updated dcrwallet rpc version for instance), although I'm not sure how that would be passed through to travis.  

Once those binaries are created and added to the bin/ directory we can start to, once again, have travis do the `yarn package` command.  With that being added back in we'll need to set up the GH_TOKEN for the repo via these instructions: https://docs.travis-ci.com/user/deployment/pages/

**Comment by matheusd** [comment] 2018-11-26 19:09
I'm not entirely sure the issue is travis as much as electron-builder (or something along its pipeline).

Do we actually want to upload the produced binaries somewhere?

For reference, this is the travis script I'm using on the weekly builds: 

https://github.com/matheusd/decred-weekly-builds/blob/master/.travis.yml

We could encode the hashes for the appropriate dcrd/dcrwallet commits and build them before decrediton or have some external repo with the binaries for each platform.

**Comment by alexlyp** [comment] 2018-11-26 19:19
Yah definitely an electron-builder issue since I tried to use "publish": "never"  and "publish": "null" but it tries to find a package that doesn't exist like "electron-publisher-never" or "electron-publisher-null".  The issue is roughly described here:  https://github.com/electron-userland/electron-builder/issues/2153  but both null and never result in the same error.

**Comment by alexlyp** [comment] 2018-11-26 20:01
Ok so apparently `"publish": null`  works  thought still not sure we even need to add this back in.

**Comment by vctt94** [comment] 2019-10-23 20:31
Now we do not use travis anymore, I believe we can close this one?

**Comment by vctt94** [comment] 2020-03-27 13:48
Closing.

**Closed by vctt94** 2020-03-27 13:48 UTC
